swagger: "2.0"
info:
  description: "API documentation for the application"
  version: "1.0.0"
  title: "EXCEL AGRII"

host: "https://excelagri.onrender.com"
basePath: "/api/v1"

tags:
  - name: "Authentication"
    description: "Authentication-related endpoints"

paths:
  /auth/register:
    post:
      tags:
        - "Authentication"
      summary: "Register a new user"
      description: "Endpoint to register a new user"
      parameters:
        - in: "body"
          name: "body"
          description: "User registration details"
          required: true
          schema:
            type: "object"
            properties:
              name:
                type: "string"
                example: "Joel Odufu"
              email:
                type: "string"
                example: "joeltest@gmail.com"
              password:
                type: "string"
                example: "joeltest@gmail.com"
      responses:
        "200":
          description: "User registered successfully"

  /auth/verifyOTP:
    post:
      tags:
        - "Authentication"
      summary: "Verify OTP"
      description: "Verify OTP for user registration"
      parameters:
        - in: "body"
          name: "body"
          description: "OTP code for verification"
          required: true
          schema:
            type: "object"
            properties:
              otpCode:
                type: "string"
                example: "498007"
      responses:
        "200":
          description: "OTP verified successfully"

  /auth/login:
    post:
      tags:
        - "Authentication"
      summary: "Login"
      description: "Authenticate user login"
      parameters:
        - in: "body"
          name: "body"
          description: "User login details"
          required: true
          schema:
            type: "object"
            properties:
              email:
                type: "string"
                example: "joeltest@gmail.com"
              password:
                type: "string"
                example: "joeltest@gmail.com"
      responses:
        "200":
          description: "User logged in successfully"

  /auth/forgotPassword:
    post:
      tags:
        - "Authentication"
      summary: "Forgot Password"
      description: "Initiate password reset"
      parameters:
        - in: "body"
          name: "body"
          description: "Email for password reset"
          required: true
          schema:
            type: "object"
            properties:
              email:
                type: "string"
                example: "joeltest@gmail.com"
      responses:
        "200":
          description: "Password reset link sent"

  /auth/resetpassword:
    post:
      tags:
        - "Authentication"
      summary: "Reset Password"
      description: "Reset user password"
      parameters:
        - in: "body"
          name: "body"
          description: "New password details"
          required: true
          schema:
            type: "object"
            properties:
              otpCode:
                type: "string"
                example: "960957"
              password:
                type: "string"
                example: "Joelleeee"
              passwordConfirm:
                type: "string"
                example: "lee"
      responses:
        "200":
          description: "Password reset successfully"
