openapi: 3.0.0
info:
  title: E X C E L API
  description: API documentation for E X C E L application.
  version: 1.2

paths:
  /api/v1/auth/signup:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
              example:
                name: "Joel Odufu"
                email: "joeltest@gmail.com"
                password: "joeltest@gmail.com"
      responses:
        '200':
          description: Successful registration
          
  /api/v1/auth/verify:
    post:
      summary: Verify OTP
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                otpCode:
                  type: string
              example:
                otpCode: "498007"
      responses:
        '200':
          description: OTP verified successfully

  /api/v1/auth/login:
    post:
      summary: Login user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              example:
                email: "joeltest@gmail.com"
                password: "joeltest@gmail.com"
      responses:
        '200':
          description: Login successful

  /api/v1/auth/forgotPassword:
    post:
      summary: Forgot Password
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
              example:
                email: "joeltest@gmail.com"
      responses:
        '200':
          description: Password reset email sent

  /api/v1/auth/resetpassword:
    post:
      summary: Reset Password
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                otpCode:
                  type: string
                password:
                  type: string
                passwordConfirm:
                  type: string
              example:
                otpCode: "960957"
                password: "Joelleeee"
                passwordConfirm: "lee"
      responses:
        '200':
          description: Password reset successful

  /api/v1/product/postproduct:
    post:
      summary: Create new product
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                Name:
                  type: string
                Description:
                  type: string
                images:
                  type: string
                _user:
                  type: string
              example:
                Name: "Shoe of shoes"
                Description: "the best of all"
                images: "image file location"
                _user: "673210c83dece75cc279bfd1"
      responses:
        '200':
          description: Product created successfully

  /api/v1/brand/postBrand:
    post:
      summary: Create new brand
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                Description:
                  type: string
                image:
                  type: string
              example:
                title: "Sednoo"
                Description: "for Shoes Only"
                image: "image file location"
      responses:
        '200':
          description: Brand created successfully

  /api/v1/cartegory/postcartegory:
    post:
      summary: Create new category
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                Description:
                  type: string
                image:
                  type: string
              example:
                title: "Category Title"
                Description: "Category description"
                image: "image file location"
      responses:
        '200':
          description: Category created successfully
